version: '3.7'
services:
  postgres:
    hostname: postgres-db
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=password
    ports:
      - '5434:5432'
    volumes:
      - my-db:/var/lib/postgresql

volumes:
  my-db:
