spring:
  application:
    name: learning-management-system
  datasource:
    password: wawzZghkuJIxiBjDpboCHrjgJDUVvqKa
    url: jdbc:postgresql://roundhouse.proxy.rlwy.net:23071/railway
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: true
  security:
    secret: bXMxNG1zMTRtczE0bXMxNG1zMTRtczE0bXMxNG1zMTRtczE0bXMxNG1zMTRtczE0bXMxNG1zMTRtczE0bXMxNA==
    token:
      expirationTime: 60
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 30GB
      max-request-size: 30GB
  mail:
    host: smtp.gmail.com
    port: 587
    username: quliyeev.n.18@gmail.com
    password: fjzlpekfwykzapdz
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true



cloud:
  aws:
    credentials:
      access-key: ${ACCESS_KEY}
      secret-key: ${SECRET_KEY}
    region:
      static: eu-north-1
    stack:
      auto: false

application:
  material:
    bucket:
      name: materiallmsbucket
  submission:
    bucket:
      name: submissionlmsbucket
